/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-21139696
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The MAC to IP setting
type MactoIp struct {
	Vmnet string `json:"vmnet"`
	Mac string `json:"mac"`
	Ip string `json:"ip"`
}
