/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-21139696
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VmUsbList struct {
	Num *Number `json:"num,omitempty"`
	UsbDevices []VmUsbDevice `json:"usbDevices,omitempty"`
}
