/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-21139696
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NicDeviceParameter struct {
	// The network type of network adapter
	Type_ string `json:"type"`
	// The vmnet name, it should only be used while type is custom
	Vmnet string `json:"vmnet"`
}
