/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-21139696
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PortforwardParameter struct {
	GuestIp string `json:"guestIp"`
	GuestPort *Port `json:"guestPort"`
	Desc string `json:"desc,omitempty"`
}
