/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-21139696
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The list of network adapters
type NicDevices struct {
	Num *NicNumber `json:"num"`
	// The network adapter added to this VM
	Nics []NicDevice `json:"nics"`
}
