/*
 * VMware Workstation REST API
 *
 * vmrest 1.3.0 build-21139696
 *
 * API version: 1.3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The CPU information of VM
type Vmcpu struct {
	Processors *VmProcessors `json:"processors,omitempty"`
}
